apiVersion: v1
data:
  config.yaml: |
    domain: mockserver-ratelimit
    descriptors:
      - key: PATH
        value: "/productpage"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: PATH
        value: "/mockserver"
        rate_limit:
          unit: minute
          requests_per_unit: 100
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 1000000
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: default
