apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-sample-provider
  labels:
    app: dubbo-sample-provider
spec:
  selector:
    matchLabels:
      app: dubbo-sample-provider
  replicas: 1
  template:
    metadata:
      labels:
        app: dubbo-sample-provider
        version: v1
    spec:
      nodeSelector:
        node.es.io/role: worker
      containers:
        - name: provider
          image: hub.easystack.cn/captain/dubbo-provider-test:v0.0.1
          imagePullPolicy: Always
          env:
            - name: AERAKI_META_APP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 20880